team_logos_hypermotion = {
    "Albacete": "https://upload.wikimedia.org/wikipedia/en/2/2f/Albacete_Balompié_logo.svg",
    "Alcorcón": "https://upload.wikimedia.org/wikipedia/en/e/e6/AD_Alcorcón_logo.svg",
    "Andorra": "https://upload.wikimedia.org/wikipedia/en/4/4f/FC_Andorra_logo.svg",
    "Burgos": "https://upload.wikimedia.org/wikipedia/en/7/76/Burgos_CF_logo.svg",
    "Cartagena": "https://upload.wikimedia.org/wikipedia/en/f/f9/FC_Cartagena_logo.svg",
    "CD Castellón": "https://upload.wikimedia.org/wikipedia/en/5/58/CD_Castellon_logo.svg",
    "CD Eldense": "https://upload.wikimedia.org/wikipedia/en/b/b4/CD_Eldense_logo.svg",
    "CD Leganés": "https://upload.wikimedia.org/wikipedia/en/d/d0/CD_Leganés_logo.svg",
    "CD Tenerife": "https://upload.wikimedia.org/wikipedia/en/f/fd/CD_Tenerife_logo.svg",
    "Deportivo de La Coruña": "https://upload.wikimedia.org/wikipedia/en/6/6f/RC_Deportivo_crest.svg",
    "Eibar": "https://upload.wikimedia.org/wikipedia/en/1/10/SD_Eibar_logo.svg",
    "Elche": "https://upload.wikimedia.org/wikipedia/en/7/72/Elche_CF_logo.svg",
    "Espanyol": "https://upload.wikimedia.org/wikipedia/en/e/e3/RCD_Espanyol_logo.svg",
    "Huesca": "https://upload.wikimedia.org/wikipedia/en/3/30/SD_Huesca_logo.svg",
    "Levante": "https://upload.wikimedia.org/wikipedia/en/5/5e/Levante_UD_logo.svg",
    "Mirandés": "https://upload.wikimedia.org/wikipedia/en/8/89/CD_Mirandés_logo.svg",
    "Oviedo": "https://upload.wikimedia.org/wikipedia/en/f/fc/Real_Oviedo_logo.svg",
    "Racing Ferrol": "https://upload.wikimedia.org/wikipedia/en/2/2c/Racing_Club_de_Ferrol_logo.svg",
    "Racing Santander": "https://upload.wikimedia.org/wikipedia/en/4/4a/Racing_de_Santander_logo.svg",
    "Real Zaragoza": "https://upload.wikimedia.org/wikipedia/en/e/e9/Real_Zaragoza_logo.svg",
    "Sporting Gijón": "https://upload.wikimedia.org/wikipedia/en/d/d6/Real_Sporting_de_Gijón_logo.svg",
    "UCAM Murcia": "https://upload.wikimedia.org/wikipedia/en/4/4c/UCAM_Murcia_CF_logo.svg"
}
